-- liquibase formatted sql

-- changeset Marsel:1758240181755-1
CREATE TABLE payment_registry
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_registry_id     BIGINT,
    paymend_date            date,
    amount                  DECIMAL(19, 2),
    interest_rate_amount    DECIMAL(19, 2),
    debt_amount             DECIMAL(19, 2),
    expired                 BOOLEAN,
    payment_expiration_date date,
    CONSTRAINT pk_payment_registry PRIMARY KEY (id)
);

-- changeset Marsel:1758240181755-2
CREATE TABLE product_registry
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    client_id     BIGINT,
    account_id    BIGINT,
    product_id    BIGINT,
    interest_rate DOUBLE PRECISION,
    open_date     date,
    CONSTRAINT pk_product_registry PRIMARY KEY (id)
);

