-- liquibase formatted sql

-- changeset Marsel:1758211053010-1
CREATE TABLE client_products
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    client_id  BIGINT,
    product_id BIGINT,
    open_date  date,
    close_date date,
    status     VARCHAR(255),
    CONSTRAINT pk_client_products PRIMARY KEY (id)
);

-- changeset Marsel:1758211053010-2
CREATE TABLE clients
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    client_id       VARCHAR(255)                            NOT NULL,
    user_id         BIGINT                                  NOT NULL,
    first_name      VARCHAR(255),
    middle_name     VARCHAR(255),
    last_name       VARCHAR(255),
    date_of_birth   date,
    document_type   VARCHAR(255),
    document_id     VARCHAR(255),
    document_prefix VARCHAR(255),
    document_suffix VARCHAR(255),
    CONSTRAINT pk_clients PRIMARY KEY (id)
);

-- changeset Marsel:1758211053010-3
CREATE TABLE products
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    key         VARCHAR(255)                            NOT NULL,
    create_date date,
    product_id  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

-- changeset Marsel:1758211053010-4
CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login    VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- changeset Marsel:1758211053010-5
ALTER TABLE clients
    ADD CONSTRAINT uc_clients_clientid UNIQUE (client_id);

-- changeset Marsel:1758211053010-6
ALTER TABLE products
    ADD CONSTRAINT uc_products_productid UNIQUE (product_id);

-- changeset Marsel:1758211053010-7
ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

-- changeset Marsel:1758211053010-8
ALTER TABLE users
    ADD CONSTRAINT uc_users_login UNIQUE (login);

